// Code generated by go-swagger; DO NOT EDIT.

package files_and_folders

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/mattx/verizon-cloud-go/client/models"
)

// NewPostMoveParams creates a new PostMoveParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostMoveParams() *PostMoveParams {
	return &PostMoveParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostMoveParamsWithTimeout creates a new PostMoveParams object
// with the ability to set a timeout on a request.
func NewPostMoveParamsWithTimeout(timeout time.Duration) *PostMoveParams {
	return &PostMoveParams{
		timeout: timeout,
	}
}

// NewPostMoveParamsWithContext creates a new PostMoveParams object
// with the ability to set a context for a request.
func NewPostMoveParamsWithContext(ctx context.Context) *PostMoveParams {
	return &PostMoveParams{
		Context: ctx,
	}
}

// NewPostMoveParamsWithHTTPClient creates a new PostMoveParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostMoveParamsWithHTTPClient(client *http.Client) *PostMoveParams {
	return &PostMoveParams{
		HTTPClient: client,
	}
}

/* PostMoveParams contains all the parameters to send to the API endpoint
   for the post move operation.

   Typically these are written to a http.Request.
*/
type PostMoveParams struct {

	/* FileMoveRequest.

	   'safe' and 'conflictsolve' are optional parameters in the request object to move a file/folder.
	*/
	FileMoveRequest *models.FopsChangeRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post move params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostMoveParams) WithDefaults() *PostMoveParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post move params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostMoveParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post move params
func (o *PostMoveParams) WithTimeout(timeout time.Duration) *PostMoveParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post move params
func (o *PostMoveParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post move params
func (o *PostMoveParams) WithContext(ctx context.Context) *PostMoveParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post move params
func (o *PostMoveParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post move params
func (o *PostMoveParams) WithHTTPClient(client *http.Client) *PostMoveParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post move params
func (o *PostMoveParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFileMoveRequest adds the fileMoveRequest to the post move params
func (o *PostMoveParams) WithFileMoveRequest(fileMoveRequest *models.FopsChangeRequest) *PostMoveParams {
	o.SetFileMoveRequest(fileMoveRequest)
	return o
}

// SetFileMoveRequest adds the fileMoveRequest to the post move params
func (o *PostMoveParams) SetFileMoveRequest(fileMoveRequest *models.FopsChangeRequest) {
	o.FileMoveRequest = fileMoveRequest
}

// WriteToRequest writes these params to a swagger request
func (o *PostMoveParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.FileMoveRequest != nil {
		if err := r.SetBodyParam(o.FileMoveRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
