// Code generated by go-swagger; DO NOT EDIT.

package playlists

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPlaylistContentParams creates a new GetPlaylistContentParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPlaylistContentParams() *GetPlaylistContentParams {
	return &GetPlaylistContentParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPlaylistContentParamsWithTimeout creates a new GetPlaylistContentParams object
// with the ability to set a timeout on a request.
func NewGetPlaylistContentParamsWithTimeout(timeout time.Duration) *GetPlaylistContentParams {
	return &GetPlaylistContentParams{
		timeout: timeout,
	}
}

// NewGetPlaylistContentParamsWithContext creates a new GetPlaylistContentParams object
// with the ability to set a context for a request.
func NewGetPlaylistContentParamsWithContext(ctx context.Context) *GetPlaylistContentParams {
	return &GetPlaylistContentParams{
		Context: ctx,
	}
}

// NewGetPlaylistContentParamsWithHTTPClient creates a new GetPlaylistContentParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPlaylistContentParamsWithHTTPClient(client *http.Client) *GetPlaylistContentParams {
	return &GetPlaylistContentParams{
		HTTPClient: client,
	}
}

/* GetPlaylistContentParams contains all the parameters to send to the API endpoint
   for the get playlist content operation.

   Typically these are written to a http.Request.
*/
type GetPlaylistContentParams struct {

	/* ItemUID.

	   Unique id related to a specific item in a playlist.
	*/
	ItemUID string

	/* PlaylistUID.

	   Unique id related to a specific playlist.
	*/
	PlaylistUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get playlist content params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPlaylistContentParams) WithDefaults() *GetPlaylistContentParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get playlist content params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPlaylistContentParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get playlist content params
func (o *GetPlaylistContentParams) WithTimeout(timeout time.Duration) *GetPlaylistContentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get playlist content params
func (o *GetPlaylistContentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get playlist content params
func (o *GetPlaylistContentParams) WithContext(ctx context.Context) *GetPlaylistContentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get playlist content params
func (o *GetPlaylistContentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get playlist content params
func (o *GetPlaylistContentParams) WithHTTPClient(client *http.Client) *GetPlaylistContentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get playlist content params
func (o *GetPlaylistContentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithItemUID adds the itemUID to the get playlist content params
func (o *GetPlaylistContentParams) WithItemUID(itemUID string) *GetPlaylistContentParams {
	o.SetItemUID(itemUID)
	return o
}

// SetItemUID adds the itemUid to the get playlist content params
func (o *GetPlaylistContentParams) SetItemUID(itemUID string) {
	o.ItemUID = itemUID
}

// WithPlaylistUID adds the playlistUID to the get playlist content params
func (o *GetPlaylistContentParams) WithPlaylistUID(playlistUID string) *GetPlaylistContentParams {
	o.SetPlaylistUID(playlistUID)
	return o
}

// SetPlaylistUID adds the playlistUid to the get playlist content params
func (o *GetPlaylistContentParams) SetPlaylistUID(playlistUID string) {
	o.PlaylistUID = playlistUID
}

// WriteToRequest writes these params to a swagger request
func (o *GetPlaylistContentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param itemUid
	if err := r.SetPathParam("itemUid", o.ItemUID); err != nil {
		return err
	}

	// path param playlistUid
	if err := r.SetPathParam("playlistUid", o.PlaylistUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
