// Code generated by go-swagger; DO NOT EDIT.

package playlists

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/MattX/verizon-cloud-go/client/models"
)

// NewPutPlaylistsParams creates a new PutPlaylistsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutPlaylistsParams() *PutPlaylistsParams {
	return &PutPlaylistsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutPlaylistsParamsWithTimeout creates a new PutPlaylistsParams object
// with the ability to set a timeout on a request.
func NewPutPlaylistsParamsWithTimeout(timeout time.Duration) *PutPlaylistsParams {
	return &PutPlaylistsParams{
		timeout: timeout,
	}
}

// NewPutPlaylistsParamsWithContext creates a new PutPlaylistsParams object
// with the ability to set a context for a request.
func NewPutPlaylistsParamsWithContext(ctx context.Context) *PutPlaylistsParams {
	return &PutPlaylistsParams{
		Context: ctx,
	}
}

// NewPutPlaylistsParamsWithHTTPClient creates a new PutPlaylistsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutPlaylistsParamsWithHTTPClient(client *http.Client) *PutPlaylistsParams {
	return &PutPlaylistsParams{
		HTTPClient: client,
	}
}

/* PutPlaylistsParams contains all the parameters to send to the API endpoint
   for the put playlists operation.

   Typically these are written to a http.Request.
*/
type PutPlaylistsParams struct {

	/* PlaylistBase.

	   Request object to update basic playlist details.
	*/
	PlaylistBase *models.PlaylistBase

	/* PlaylistUID.

	   Unique id related to a specific playlist.
	*/
	PlaylistUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put playlists params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutPlaylistsParams) WithDefaults() *PutPlaylistsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put playlists params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutPlaylistsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put playlists params
func (o *PutPlaylistsParams) WithTimeout(timeout time.Duration) *PutPlaylistsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put playlists params
func (o *PutPlaylistsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put playlists params
func (o *PutPlaylistsParams) WithContext(ctx context.Context) *PutPlaylistsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put playlists params
func (o *PutPlaylistsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put playlists params
func (o *PutPlaylistsParams) WithHTTPClient(client *http.Client) *PutPlaylistsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put playlists params
func (o *PutPlaylistsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPlaylistBase adds the playlistBase to the put playlists params
func (o *PutPlaylistsParams) WithPlaylistBase(playlistBase *models.PlaylistBase) *PutPlaylistsParams {
	o.SetPlaylistBase(playlistBase)
	return o
}

// SetPlaylistBase adds the playlistBase to the put playlists params
func (o *PutPlaylistsParams) SetPlaylistBase(playlistBase *models.PlaylistBase) {
	o.PlaylistBase = playlistBase
}

// WithPlaylistUID adds the playlistUID to the put playlists params
func (o *PutPlaylistsParams) WithPlaylistUID(playlistUID string) *PutPlaylistsParams {
	o.SetPlaylistUID(playlistUID)
	return o
}

// SetPlaylistUID adds the playlistUid to the put playlists params
func (o *PutPlaylistsParams) SetPlaylistUID(playlistUID string) {
	o.PlaylistUID = playlistUID
}

// WriteToRequest writes these params to a swagger request
func (o *PutPlaylistsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.PlaylistBase != nil {
		if err := r.SetBodyParam(o.PlaylistBase); err != nil {
			return err
		}
	}

	// path param playlistUid
	if err := r.SetPathParam("playlistUid", o.PlaylistUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
