// Code generated by go-swagger; DO NOT EDIT.

package contacts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/MattX/verizon-cloud-go/client/models"
)

// GetContactDeltaReader is a Reader for the GetContactDelta structure.
type GetContactDeltaReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetContactDeltaReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetContactDeltaOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 204:
		result := NewGetContactDeltaNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetContactDeltaBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetContactDeltaUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetContactDeltaInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewGetContactDeltaServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetContactDeltaOK creates a GetContactDeltaOK with default headers values
func NewGetContactDeltaOK() *GetContactDeltaOK {
	return &GetContactDeltaOK{}
}

/* GetContactDeltaOK describes a response with status code 200, with default header values.

OK
*/
type GetContactDeltaOK struct {
	Payload *models.ContactsDelta
}

func (o *GetContactDeltaOK) Error() string {
	return fmt.Sprintf("[GET /contacthistory][%d] getContactDeltaOK  %+v", 200, o.Payload)
}
func (o *GetContactDeltaOK) GetPayload() *models.ContactsDelta {
	return o.Payload
}

func (o *GetContactDeltaOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ContactsDelta)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetContactDeltaNoContent creates a GetContactDeltaNoContent with default headers values
func NewGetContactDeltaNoContent() *GetContactDeltaNoContent {
	return &GetContactDeltaNoContent{}
}

/* GetContactDeltaNoContent describes a response with status code 204, with default header values.

OK. No changes are to be reported in the requested type.
*/
type GetContactDeltaNoContent struct {
}

func (o *GetContactDeltaNoContent) Error() string {
	return fmt.Sprintf("[GET /contacthistory][%d] getContactDeltaNoContent ", 204)
}

func (o *GetContactDeltaNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetContactDeltaBadRequest creates a GetContactDeltaBadRequest with default headers values
func NewGetContactDeltaBadRequest() *GetContactDeltaBadRequest {
	return &GetContactDeltaBadRequest{}
}

/* GetContactDeltaBadRequest describes a response with status code 400, with default header values.

[Bad Request] Query parameters missing or invalid.
*/
type GetContactDeltaBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *GetContactDeltaBadRequest) Error() string {
	return fmt.Sprintf("[GET /contacthistory][%d] getContactDeltaBadRequest  %+v", 400, o.Payload)
}
func (o *GetContactDeltaBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetContactDeltaBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetContactDeltaUnauthorized creates a GetContactDeltaUnauthorized with default headers values
func NewGetContactDeltaUnauthorized() *GetContactDeltaUnauthorized {
	return &GetContactDeltaUnauthorized{}
}

/* GetContactDeltaUnauthorized describes a response with status code 401, with default header values.

[Unauthorized] Bearer token is missing, expired, or invalid.
*/
type GetContactDeltaUnauthorized struct {
	Payload *models.ErrorResponse
}

func (o *GetContactDeltaUnauthorized) Error() string {
	return fmt.Sprintf("[GET /contacthistory][%d] getContactDeltaUnauthorized  %+v", 401, o.Payload)
}
func (o *GetContactDeltaUnauthorized) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetContactDeltaUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetContactDeltaInternalServerError creates a GetContactDeltaInternalServerError with default headers values
func NewGetContactDeltaInternalServerError() *GetContactDeltaInternalServerError {
	return &GetContactDeltaInternalServerError{}
}

/* GetContactDeltaInternalServerError describes a response with status code 500, with default header values.

Unexpected Account configuration.
*/
type GetContactDeltaInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *GetContactDeltaInternalServerError) Error() string {
	return fmt.Sprintf("[GET /contacthistory][%d] getContactDeltaInternalServerError  %+v", 500, o.Payload)
}
func (o *GetContactDeltaInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetContactDeltaInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetContactDeltaServiceUnavailable creates a GetContactDeltaServiceUnavailable with default headers values
func NewGetContactDeltaServiceUnavailable() *GetContactDeltaServiceUnavailable {
	return &GetContactDeltaServiceUnavailable{}
}

/* GetContactDeltaServiceUnavailable describes a response with status code 503, with default header values.

[Service Unavailable] See response body for more detail.
*/
type GetContactDeltaServiceUnavailable struct {
	Payload *models.ErrorResponse
}

func (o *GetContactDeltaServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /contacthistory][%d] getContactDeltaServiceUnavailable  %+v", 503, o.Payload)
}
func (o *GetContactDeltaServiceUnavailable) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetContactDeltaServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
