// Code generated by go-swagger; DO NOT EDIT.

package shares

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteShareParams creates a new DeleteShareParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteShareParams() *DeleteShareParams {
	return &DeleteShareParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteShareParamsWithTimeout creates a new DeleteShareParams object
// with the ability to set a timeout on a request.
func NewDeleteShareParamsWithTimeout(timeout time.Duration) *DeleteShareParams {
	return &DeleteShareParams{
		timeout: timeout,
	}
}

// NewDeleteShareParamsWithContext creates a new DeleteShareParams object
// with the ability to set a context for a request.
func NewDeleteShareParamsWithContext(ctx context.Context) *DeleteShareParams {
	return &DeleteShareParams{
		Context: ctx,
	}
}

// NewDeleteShareParamsWithHTTPClient creates a new DeleteShareParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteShareParamsWithHTTPClient(client *http.Client) *DeleteShareParams {
	return &DeleteShareParams{
		HTTPClient: client,
	}
}

/* DeleteShareParams contains all the parameters to send to the API endpoint
   for the delete share operation.

   Typically these are written to a http.Request.
*/
type DeleteShareParams struct {

	/* ShareUID.

	   The unique ID of the share.
	*/
	ShareUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete share params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteShareParams) WithDefaults() *DeleteShareParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete share params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteShareParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete share params
func (o *DeleteShareParams) WithTimeout(timeout time.Duration) *DeleteShareParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete share params
func (o *DeleteShareParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete share params
func (o *DeleteShareParams) WithContext(ctx context.Context) *DeleteShareParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete share params
func (o *DeleteShareParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete share params
func (o *DeleteShareParams) WithHTTPClient(client *http.Client) *DeleteShareParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete share params
func (o *DeleteShareParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithShareUID adds the shareUID to the delete share params
func (o *DeleteShareParams) WithShareUID(shareUID string) *DeleteShareParams {
	o.SetShareUID(shareUID)
	return o
}

// SetShareUID adds the shareUid to the delete share params
func (o *DeleteShareParams) SetShareUID(shareUID string) {
	o.ShareUID = shareUID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteShareParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param shareUid
	if err := r.SetPathParam("shareUid", o.ShareUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
