// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ContactsEmail contacts email
//
// swagger:model contacts_email
type ContactsEmail struct {

	// Email address
	// Required: true
	Address *string `json:"address"`

	// When combined with 'type', provides a unique identifier for the entry
	// Required: true
	Indx *int64 `json:"indx"`

	// For sorting. Lower numbers indicate a higher preference. The value must be less than 100.
	// Required: true
	Preference *int64 `json:"preference"`

	// Type of email address, i.e., 'business', 'personal', 'other'.
	// Required: true
	Type *string `json:"type"`
}

// Validate validates this contacts email
func (m *ContactsEmail) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAddress(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIndx(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePreference(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ContactsEmail) validateAddress(formats strfmt.Registry) error {

	if err := validate.Required("address", "body", m.Address); err != nil {
		return err
	}

	return nil
}

func (m *ContactsEmail) validateIndx(formats strfmt.Registry) error {

	if err := validate.Required("indx", "body", m.Indx); err != nil {
		return err
	}

	return nil
}

func (m *ContactsEmail) validatePreference(formats strfmt.Registry) error {

	if err := validate.Required("preference", "body", m.Preference); err != nil {
		return err
	}

	return nil
}

func (m *ContactsEmail) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this contacts email based on context it is used
func (m *ContactsEmail) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ContactsEmail) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ContactsEmail) UnmarshalBinary(b []byte) error {
	var res ContactsEmail
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
