// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// FlashbackList flashback list
//
// swagger:model flashback_list
type FlashbackList struct {

	// year
	Year []*ImageFlashbackResponse `json:"<year>"`
}

// Validate validates this flashback list
func (m *FlashbackList) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateYear(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FlashbackList) validateYear(formats strfmt.Registry) error {
	if swag.IsZero(m.Year) { // not required
		return nil
	}

	for i := 0; i < len(m.Year); i++ {
		if swag.IsZero(m.Year[i]) { // not required
			continue
		}

		if m.Year[i] != nil {
			if err := m.Year[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("<year>" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("<year>" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this flashback list based on the context it is used
func (m *FlashbackList) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateYear(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FlashbackList) contextValidateYear(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Year); i++ {

		if m.Year[i] != nil {
			if err := m.Year[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("<year>" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("<year>" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *FlashbackList) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FlashbackList) UnmarshalBinary(b []byte) error {
	var res FlashbackList
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
