// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// FolderMetadata folder metadata
//
// swagger:model folder_metadata
type FolderMetadata struct {
	BaseFolderMetadata

	// Array of shareAssociation
	ShareAssociation []*FolderMetadataShareAssociationItems0 `json:"shareAssociation"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *FolderMetadata) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 BaseFolderMetadata
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.BaseFolderMetadata = aO0

	// AO1
	var dataAO1 struct {
		ShareAssociation []*FolderMetadataShareAssociationItems0 `json:"shareAssociation"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.ShareAssociation = dataAO1.ShareAssociation

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m FolderMetadata) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.BaseFolderMetadata)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	var dataAO1 struct {
		ShareAssociation []*FolderMetadataShareAssociationItems0 `json:"shareAssociation"`
	}

	dataAO1.ShareAssociation = m.ShareAssociation

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this folder metadata
func (m *FolderMetadata) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with BaseFolderMetadata
	if err := m.BaseFolderMetadata.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateShareAssociation(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FolderMetadata) validateShareAssociation(formats strfmt.Registry) error {

	if swag.IsZero(m.ShareAssociation) { // not required
		return nil
	}

	for i := 0; i < len(m.ShareAssociation); i++ {
		if swag.IsZero(m.ShareAssociation[i]) { // not required
			continue
		}

		if m.ShareAssociation[i] != nil {
			if err := m.ShareAssociation[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("shareAssociation" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("shareAssociation" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this folder metadata based on the context it is used
func (m *FolderMetadata) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with BaseFolderMetadata
	if err := m.BaseFolderMetadata.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateShareAssociation(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FolderMetadata) contextValidateShareAssociation(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ShareAssociation); i++ {

		if m.ShareAssociation[i] != nil {
			if err := m.ShareAssociation[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("shareAssociation" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("shareAssociation" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *FolderMetadata) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FolderMetadata) UnmarshalBinary(b []byte) error {
	var res FolderMetadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// FolderMetadataShareAssociationItems0 folder metadata share association items0
//
// swagger:model FolderMetadataShareAssociationItems0
type FolderMetadataShareAssociationItems0 struct {

	// Name
	// Required: true
	Name *string `json:"name"`

	// Type of share association
	// Required: true
	Type *string `json:"type"`

	// Unique id
	// Required: true
	UID *string `json:"uid"`

	// Visibility of share association
	// Required: true
	Visibility *string `json:"visibility"`
}

// Validate validates this folder metadata share association items0
func (m *FolderMetadataShareAssociationItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVisibility(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FolderMetadataShareAssociationItems0) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *FolderMetadataShareAssociationItems0) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

func (m *FolderMetadataShareAssociationItems0) validateUID(formats strfmt.Registry) error {

	if err := validate.Required("uid", "body", m.UID); err != nil {
		return err
	}

	return nil
}

func (m *FolderMetadataShareAssociationItems0) validateVisibility(formats strfmt.Registry) error {

	if err := validate.Required("visibility", "body", m.Visibility); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this folder metadata share association items0 based on context it is used
func (m *FolderMetadataShareAssociationItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FolderMetadataShareAssociationItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FolderMetadataShareAssociationItems0) UnmarshalBinary(b []byte) error {
	var res FolderMetadataShareAssociationItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
