// Code generated by go-swagger; DO NOT EDIT.

package files_and_folders

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetFullviewParams creates a new GetFullviewParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetFullviewParams() *GetFullviewParams {
	return &GetFullviewParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetFullviewParamsWithTimeout creates a new GetFullviewParams object
// with the ability to set a timeout on a request.
func NewGetFullviewParamsWithTimeout(timeout time.Duration) *GetFullviewParams {
	return &GetFullviewParams{
		timeout: timeout,
	}
}

// NewGetFullviewParamsWithContext creates a new GetFullviewParams object
// with the ability to set a context for a request.
func NewGetFullviewParamsWithContext(ctx context.Context) *GetFullviewParams {
	return &GetFullviewParams{
		Context: ctx,
	}
}

// NewGetFullviewParamsWithHTTPClient creates a new GetFullviewParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetFullviewParamsWithHTTPClient(client *http.Client) *GetFullviewParams {
	return &GetFullviewParams{
		HTTPClient: client,
	}
}

/* GetFullviewParams contains all the parameters to send to the API endpoint
   for the get fullview operation.

   Typically these are written to a http.Request.
*/
type GetFullviewParams struct {

	/* XHeaderETag.

	   Omit this header to request a full response.  To request only changes since a previous call to fullview, include this header as copied from your previous /fullview response.
	*/
	XHeaderETag *string

	/* Virtualfolder.

	   Folder that represents various client types at the root level and contains their respective data. Defaulted to VZMOBILE.
	*/
	Virtualfolder *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get fullview params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFullviewParams) WithDefaults() *GetFullviewParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get fullview params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFullviewParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get fullview params
func (o *GetFullviewParams) WithTimeout(timeout time.Duration) *GetFullviewParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get fullview params
func (o *GetFullviewParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get fullview params
func (o *GetFullviewParams) WithContext(ctx context.Context) *GetFullviewParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get fullview params
func (o *GetFullviewParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get fullview params
func (o *GetFullviewParams) WithHTTPClient(client *http.Client) *GetFullviewParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get fullview params
func (o *GetFullviewParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXHeaderETag adds the xHeaderETag to the get fullview params
func (o *GetFullviewParams) WithXHeaderETag(xHeaderETag *string) *GetFullviewParams {
	o.SetXHeaderETag(xHeaderETag)
	return o
}

// SetXHeaderETag adds the xHeaderETag to the get fullview params
func (o *GetFullviewParams) SetXHeaderETag(xHeaderETag *string) {
	o.XHeaderETag = xHeaderETag
}

// WithVirtualfolder adds the virtualfolder to the get fullview params
func (o *GetFullviewParams) WithVirtualfolder(virtualfolder *string) *GetFullviewParams {
	o.SetVirtualfolder(virtualfolder)
	return o
}

// SetVirtualfolder adds the virtualfolder to the get fullview params
func (o *GetFullviewParams) SetVirtualfolder(virtualfolder *string) {
	o.Virtualfolder = virtualfolder
}

// WriteToRequest writes these params to a swagger request
func (o *GetFullviewParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XHeaderETag != nil {

		// header param X-Header-ETag
		if err := r.SetHeaderParam("X-Header-ETag", *o.XHeaderETag); err != nil {
			return err
		}
	}

	if o.Virtualfolder != nil {

		// query param virtualfolder
		var qrVirtualfolder string

		if o.Virtualfolder != nil {
			qrVirtualfolder = *o.Virtualfolder
		}
		qVirtualfolder := qrVirtualfolder
		if qVirtualfolder != "" {

			if err := r.SetQueryParam("virtualfolder", qVirtualfolder); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
