// Code generated by go-swagger; DO NOT EDIT.

package files_and_folders

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/mattx/verizon-cloud-go/client/models"
)

// NewPostCreatefolderParams creates a new PostCreatefolderParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostCreatefolderParams() *PostCreatefolderParams {
	return &PostCreatefolderParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostCreatefolderParamsWithTimeout creates a new PostCreatefolderParams object
// with the ability to set a timeout on a request.
func NewPostCreatefolderParamsWithTimeout(timeout time.Duration) *PostCreatefolderParams {
	return &PostCreatefolderParams{
		timeout: timeout,
	}
}

// NewPostCreatefolderParamsWithContext creates a new PostCreatefolderParams object
// with the ability to set a context for a request.
func NewPostCreatefolderParamsWithContext(ctx context.Context) *PostCreatefolderParams {
	return &PostCreatefolderParams{
		Context: ctx,
	}
}

// NewPostCreatefolderParamsWithHTTPClient creates a new PostCreatefolderParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostCreatefolderParamsWithHTTPClient(client *http.Client) *PostCreatefolderParams {
	return &PostCreatefolderParams{
		HTTPClient: client,
	}
}

/* PostCreatefolderParams contains all the parameters to send to the API endpoint
   for the post createfolder operation.

   Typically these are written to a http.Request.
*/
type PostCreatefolderParams struct {

	/* Folder.

	   'override' is an optional parameter in the request object to create a folder.
	*/
	Folder *models.FolderRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post createfolder params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostCreatefolderParams) WithDefaults() *PostCreatefolderParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post createfolder params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostCreatefolderParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post createfolder params
func (o *PostCreatefolderParams) WithTimeout(timeout time.Duration) *PostCreatefolderParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post createfolder params
func (o *PostCreatefolderParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post createfolder params
func (o *PostCreatefolderParams) WithContext(ctx context.Context) *PostCreatefolderParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post createfolder params
func (o *PostCreatefolderParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post createfolder params
func (o *PostCreatefolderParams) WithHTTPClient(client *http.Client) *PostCreatefolderParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post createfolder params
func (o *PostCreatefolderParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFolder adds the folder to the post createfolder params
func (o *PostCreatefolderParams) WithFolder(folder *models.FolderRequest) *PostCreatefolderParams {
	o.SetFolder(folder)
	return o
}

// SetFolder adds the folder to the post createfolder params
func (o *PostCreatefolderParams) SetFolder(folder *models.FolderRequest) {
	o.Folder = folder
}

// WriteToRequest writes these params to a swagger request
func (o *PostCreatefolderParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Folder != nil {
		if err := r.SetBodyParam(o.Folder); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
