// Code generated by go-swagger; DO NOT EDIT.

package files_and_folders

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewRetrieveTrashParams creates a new RetrieveTrashParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRetrieveTrashParams() *RetrieveTrashParams {
	return &RetrieveTrashParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRetrieveTrashParamsWithTimeout creates a new RetrieveTrashParams object
// with the ability to set a timeout on a request.
func NewRetrieveTrashParamsWithTimeout(timeout time.Duration) *RetrieveTrashParams {
	return &RetrieveTrashParams{
		timeout: timeout,
	}
}

// NewRetrieveTrashParamsWithContext creates a new RetrieveTrashParams object
// with the ability to set a context for a request.
func NewRetrieveTrashParamsWithContext(ctx context.Context) *RetrieveTrashParams {
	return &RetrieveTrashParams{
		Context: ctx,
	}
}

// NewRetrieveTrashParamsWithHTTPClient creates a new RetrieveTrashParams object
// with the ability to set a custom HTTPClient for a request.
func NewRetrieveTrashParamsWithHTTPClient(client *http.Client) *RetrieveTrashParams {
	return &RetrieveTrashParams{
		HTTPClient: client,
	}
}

/* RetrieveTrashParams contains all the parameters to send to the API endpoint
   for the retrieve trash operation.

   Typically these are written to a http.Request.
*/
type RetrieveTrashParams struct {

	/* Count.

	   Maximum children to include in a paginated response.  Defaulted to 20 if page is specified.
	*/
	Count *int64

	/* Deep.

	   Specifies whether the search should stop at the topmost deleted item in the tree (deep=false), or navigate into it and list all the deleted contents    (deep=true).
	*/
	Deep *bool

	/* Filter.

	   Set to 'file' or 'folder', to include only those types of items in the response.
	*/
	Filter *string

	/* Page.

	   Page number to return, for paginated responses. Defaulted to 1 if count is specified.
	*/
	Page *int64

	/* Sort.

	   Controls the sort order in which the response is returned. Uses the syntax: sort={field}+(asc|desc).Valid values for 'field' are: name, versionCreated, size, extension, album, artist, captureDate, contentType, creationDate, genre, priority, title, timelineDate
	*/
	Sort *string

	/* Virtualfolder.

	   Folder that represents various client types at the root level and contains their respective data.
	*/
	Virtualfolder string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the retrieve trash params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RetrieveTrashParams) WithDefaults() *RetrieveTrashParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the retrieve trash params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RetrieveTrashParams) SetDefaults() {
	var (
		deepDefault = bool(false)
	)

	val := RetrieveTrashParams{
		Deep: &deepDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the retrieve trash params
func (o *RetrieveTrashParams) WithTimeout(timeout time.Duration) *RetrieveTrashParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the retrieve trash params
func (o *RetrieveTrashParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the retrieve trash params
func (o *RetrieveTrashParams) WithContext(ctx context.Context) *RetrieveTrashParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the retrieve trash params
func (o *RetrieveTrashParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the retrieve trash params
func (o *RetrieveTrashParams) WithHTTPClient(client *http.Client) *RetrieveTrashParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the retrieve trash params
func (o *RetrieveTrashParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCount adds the count to the retrieve trash params
func (o *RetrieveTrashParams) WithCount(count *int64) *RetrieveTrashParams {
	o.SetCount(count)
	return o
}

// SetCount adds the count to the retrieve trash params
func (o *RetrieveTrashParams) SetCount(count *int64) {
	o.Count = count
}

// WithDeep adds the deep to the retrieve trash params
func (o *RetrieveTrashParams) WithDeep(deep *bool) *RetrieveTrashParams {
	o.SetDeep(deep)
	return o
}

// SetDeep adds the deep to the retrieve trash params
func (o *RetrieveTrashParams) SetDeep(deep *bool) {
	o.Deep = deep
}

// WithFilter adds the filter to the retrieve trash params
func (o *RetrieveTrashParams) WithFilter(filter *string) *RetrieveTrashParams {
	o.SetFilter(filter)
	return o
}

// SetFilter adds the filter to the retrieve trash params
func (o *RetrieveTrashParams) SetFilter(filter *string) {
	o.Filter = filter
}

// WithPage adds the page to the retrieve trash params
func (o *RetrieveTrashParams) WithPage(page *int64) *RetrieveTrashParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the retrieve trash params
func (o *RetrieveTrashParams) SetPage(page *int64) {
	o.Page = page
}

// WithSort adds the sort to the retrieve trash params
func (o *RetrieveTrashParams) WithSort(sort *string) *RetrieveTrashParams {
	o.SetSort(sort)
	return o
}

// SetSort adds the sort to the retrieve trash params
func (o *RetrieveTrashParams) SetSort(sort *string) {
	o.Sort = sort
}

// WithVirtualfolder adds the virtualfolder to the retrieve trash params
func (o *RetrieveTrashParams) WithVirtualfolder(virtualfolder string) *RetrieveTrashParams {
	o.SetVirtualfolder(virtualfolder)
	return o
}

// SetVirtualfolder adds the virtualfolder to the retrieve trash params
func (o *RetrieveTrashParams) SetVirtualfolder(virtualfolder string) {
	o.Virtualfolder = virtualfolder
}

// WriteToRequest writes these params to a swagger request
func (o *RetrieveTrashParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Count != nil {

		// query param count
		var qrCount int64

		if o.Count != nil {
			qrCount = *o.Count
		}
		qCount := swag.FormatInt64(qrCount)
		if qCount != "" {

			if err := r.SetQueryParam("count", qCount); err != nil {
				return err
			}
		}
	}

	if o.Deep != nil {

		// query param deep
		var qrDeep bool

		if o.Deep != nil {
			qrDeep = *o.Deep
		}
		qDeep := swag.FormatBool(qrDeep)
		if qDeep != "" {

			if err := r.SetQueryParam("deep", qDeep); err != nil {
				return err
			}
		}
	}

	if o.Filter != nil {

		// query param filter
		var qrFilter string

		if o.Filter != nil {
			qrFilter = *o.Filter
		}
		qFilter := qrFilter
		if qFilter != "" {

			if err := r.SetQueryParam("filter", qFilter); err != nil {
				return err
			}
		}
	}

	if o.Page != nil {

		// query param page
		var qrPage int64

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if o.Sort != nil {

		// query param sort
		var qrSort string

		if o.Sort != nil {
			qrSort = *o.Sort
		}
		qSort := qrSort
		if qSort != "" {

			if err := r.SetQueryParam("sort", qSort); err != nil {
				return err
			}
		}
	}

	// query param virtualfolder
	qrVirtualfolder := o.Virtualfolder
	qVirtualfolder := qrVirtualfolder
	if qVirtualfolder != "" {

		if err := r.SetQueryParam("virtualfolder", qVirtualfolder); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
