// Code generated by go-swagger; DO NOT EDIT.

package favorites

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mattx/verizon-cloud-go/models"
)

// DeleteFavoritesReader is a Reader for the DeleteFavorites structure.
type DeleteFavoritesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteFavoritesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteFavoritesNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteFavoritesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteFavoritesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteFavoritesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteFavoritesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewDeleteFavoritesServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteFavoritesNoContent creates a DeleteFavoritesNoContent with default headers values
func NewDeleteFavoritesNoContent() *DeleteFavoritesNoContent {
	return &DeleteFavoritesNoContent{}
}

/* DeleteFavoritesNoContent describes a response with status code 204, with default header values.

OK.
*/
type DeleteFavoritesNoContent struct {
}

func (o *DeleteFavoritesNoContent) Error() string {
	return fmt.Sprintf("[DELETE /favorites][%d] deleteFavoritesNoContent ", 204)
}

func (o *DeleteFavoritesNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteFavoritesBadRequest creates a DeleteFavoritesBadRequest with default headers values
func NewDeleteFavoritesBadRequest() *DeleteFavoritesBadRequest {
	return &DeleteFavoritesBadRequest{}
}

/* DeleteFavoritesBadRequest describes a response with status code 400, with default header values.

[Bad Request] Query parameters missing or invalid.
*/
type DeleteFavoritesBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *DeleteFavoritesBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /favorites][%d] deleteFavoritesBadRequest  %+v", 400, o.Payload)
}
func (o *DeleteFavoritesBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteFavoritesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteFavoritesUnauthorized creates a DeleteFavoritesUnauthorized with default headers values
func NewDeleteFavoritesUnauthorized() *DeleteFavoritesUnauthorized {
	return &DeleteFavoritesUnauthorized{}
}

/* DeleteFavoritesUnauthorized describes a response with status code 401, with default header values.

[Unauthorized] Bearer token is missing, expired, or invalid.
*/
type DeleteFavoritesUnauthorized struct {
	Payload *models.ErrorResponse
}

func (o *DeleteFavoritesUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /favorites][%d] deleteFavoritesUnauthorized  %+v", 401, o.Payload)
}
func (o *DeleteFavoritesUnauthorized) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteFavoritesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteFavoritesForbidden creates a DeleteFavoritesForbidden with default headers values
func NewDeleteFavoritesForbidden() *DeleteFavoritesForbidden {
	return &DeleteFavoritesForbidden{}
}

/* DeleteFavoritesForbidden describes a response with status code 403, with default header values.

[Forbidden] User is not authorized to access storage APIs.
*/
type DeleteFavoritesForbidden struct {
	Payload *models.ErrorResponse
}

func (o *DeleteFavoritesForbidden) Error() string {
	return fmt.Sprintf("[DELETE /favorites][%d] deleteFavoritesForbidden  %+v", 403, o.Payload)
}
func (o *DeleteFavoritesForbidden) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteFavoritesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteFavoritesNotFound creates a DeleteFavoritesNotFound with default headers values
func NewDeleteFavoritesNotFound() *DeleteFavoritesNotFound {
	return &DeleteFavoritesNotFound{}
}

/* DeleteFavoritesNotFound describes a response with status code 404, with default header values.

[Not Found] File or folder was not found.
*/
type DeleteFavoritesNotFound struct {
	Payload *models.ErrorResponse
}

func (o *DeleteFavoritesNotFound) Error() string {
	return fmt.Sprintf("[DELETE /favorites][%d] deleteFavoritesNotFound  %+v", 404, o.Payload)
}
func (o *DeleteFavoritesNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteFavoritesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteFavoritesServiceUnavailable creates a DeleteFavoritesServiceUnavailable with default headers values
func NewDeleteFavoritesServiceUnavailable() *DeleteFavoritesServiceUnavailable {
	return &DeleteFavoritesServiceUnavailable{}
}

/* DeleteFavoritesServiceUnavailable describes a response with status code 503, with default header values.

[Service Unavailable] See response body for more detail.
*/
type DeleteFavoritesServiceUnavailable struct {
	Payload *models.ErrorResponse
}

func (o *DeleteFavoritesServiceUnavailable) Error() string {
	return fmt.Sprintf("[DELETE /favorites][%d] deleteFavoritesServiceUnavailable  %+v", 503, o.Payload)
}
func (o *DeleteFavoritesServiceUnavailable) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteFavoritesServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
