// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// FlashbackResponse flashback response
//
// swagger:model flashback_response
type FlashbackResponse struct {

	// A set of images for each time frame
	Flashback *FlashbackList `json:"flashback,omitempty"`

	// The latest captured image having image score
	// Required: true
	Latest *ImageFlashbackResponse `json:"latest"`
}

// Validate validates this flashback response
func (m *FlashbackResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFlashback(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLatest(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FlashbackResponse) validateFlashback(formats strfmt.Registry) error {
	if swag.IsZero(m.Flashback) { // not required
		return nil
	}

	if m.Flashback != nil {
		if err := m.Flashback.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("flashback")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("flashback")
			}
			return err
		}
	}

	return nil
}

func (m *FlashbackResponse) validateLatest(formats strfmt.Registry) error {

	if err := validate.Required("latest", "body", m.Latest); err != nil {
		return err
	}

	if m.Latest != nil {
		if err := m.Latest.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("latest")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("latest")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this flashback response based on the context it is used
func (m *FlashbackResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateFlashback(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateLatest(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FlashbackResponse) contextValidateFlashback(ctx context.Context, formats strfmt.Registry) error {

	if m.Flashback != nil {
		if err := m.Flashback.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("flashback")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("flashback")
			}
			return err
		}
	}

	return nil
}

func (m *FlashbackResponse) contextValidateLatest(ctx context.Context, formats strfmt.Registry) error {

	if m.Latest != nil {
		if err := m.Latest.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("latest")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("latest")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *FlashbackResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FlashbackResponse) UnmarshalBinary(b []byte) error {
	var res FlashbackResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
