// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UpdateFavoriteRequest update favorite request
//
// swagger:model updateFavorite_request
type UpdateFavoriteRequest struct {

	// If 'true', creates a new version of the file or folder. Defaults to 'false'.
	CreateVersion *bool `json:"createVersion,omitempty"`

	// URI of the resource. This is a URI value obtained from a fullview or metadata response
	// Required: true
	URI []string `json:"uri"`
}

// Validate validates this update favorite request
func (m *UpdateFavoriteRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateURI(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UpdateFavoriteRequest) validateURI(formats strfmt.Registry) error {

	if err := validate.Required("uri", "body", m.URI); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this update favorite request based on context it is used
func (m *UpdateFavoriteRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateFavoriteRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateFavoriteRequest) UnmarshalBinary(b []byte) error {
	var res UpdateFavoriteRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
